packages:
  - 'server'
  - 'database-server'
  - 'ui'
allowBuilds:
  embedded-postgres: true
  '@embedded-postgres/darwin-arm64': true
  '@embedded-postgres/darwin-x64': true
  '@embedded-postgres/linux-arm64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/windows-x64': true
  '@firebase/util': true
  '@tailwindcss/oxide': true
  es5-ext: true
  esbuild: true
  protobufjs: true
  re2: true
  sharp: true
  workerd: true
